/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_ArgsScreen
#define HEADER_ArgsScreen

#include "InfoScreen.h"

typedef struct ArgsScreen_ {
   InfoScreen super;
} ArgsScreen;

extern InfoScreenClass ArgsScreen_class;

ArgsScreen* ArgsScreen_new(Process* process);

void ArgsScreen_delete(Object* this);

void ArgsScreen_draw(InfoScreen* this);

void ArgsScreen_scan(InfoScreen* this);

#endif
